name: string-tension CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install FLTK headers
      run: sudo apt-get install -y libfltk1.3-dev
    - name: make
      run: make
