name: string-tension CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: sudo apt-get install -y libfltk1.3-dev libgtest-dev libxinerama-dev libxcursor-dev libxfixes-dev libxft-dev
    - name: Run library tests
      run: |
        make test
        ./build/test
    - name: make
      run: make
