name: build release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: sudo apt-get install -y libfltk1.3-dev libgtest-dev libxinerama-dev libxcursor-dev libxfixes-dev libxft-dev
    - name: make
      run: make
    - name: package
      run: |
        mv build/string-tension string-tension
        tar -czf string-tension.tar.gz README.md LICENSE string-tension
    - uses: actions/github-script@v7
      env: 
        RELEASE_ID: ${{github.event.release.id}}
      with:
        script: |
          const fs = require('fs');
          await github.rest.repos.uploadReleaseAsset({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: process.env.RELEASE_ID,
            name: "string-tension_" + process.env.GITHUB_REF_NAME + "_linux64bit.tar.gz",
            data: fs.readFileSync("string-tension.tar.gz")
          });
